vehicle_map_2 = {
    "Nissan": {
        "seating_capacity": {
            "almera": 5,
            "ad wagon y11": 5,
            "aura": 5,
            "cefiro": 5,
            "clipper": 5,
            "dayz": 5,
            "dayz highway star": 4,
            "juke": 5,
            "kicks": 5,
            "lafesta": 7,
            "leaf acenta": 5,
            "leaf": 5,
            "magnite": 5,
            "march": 5,
            "navara": 5,
            "note": 5,
            "aura": 5,
            "patrol": 7,
            "primera": 5,
            "qashqai tekna": 5,
            ",roox highway star": 4,
            "sakura": 4,
            "serena e power hs": 7,
            "sunny": 5,
            "sylphy": 5,
            "tiida": 5,
            "x-trail": 5,
        },
        "body_type": {
            "almera": "sedan",
            "ad wagon y11": "station wagon",
            "aura": "hatchback",
            "cefiro": "sedan",
            "clipper": "kei/minivan",
            "dayz": "hatchback",
            "juke": "suv",
            "kicks": "suv",
            "lafesta": "muv",
            "leaf": "hatchback",
            "magnite": "suv",
            "march": "hatchback",
            "navara": "pickup",
            "note": "hatchback",
            "aura": "hatchback",
            "patrol": "suv",
            "primera": "hatchback/sedan/wagon",
            "qashqai tekna": "suv",
            ",roox highway star": "kei",
            "sakura": "kei",
            "serena e power hs v": "minivan",
            "sunny": "sedan",
            "sylphy": "sedan",
            "tiida": "hatchback",
            "tiida latio": "sedan",
            "x-trail": "suv",
        },
        "ground_clearance": {"almera": {"min": 121, "max": 136}},
    },
    "Perodua": {
        "seating_capacity": {"axia": 5, "beeza": 5, "viva elite": 5},
        "body_type": {"axia": "hatchback", "beeza": "sedan", "viva elite": "hatchback"},
        "ground_clearance": {},
    },
    "Peugeot": {
        "seating_capacity": {
            "2008": 5,
            "3008": 5,
            "306 wagon": 5,
            "306": 5,
            "406": 5,
            "5008": 7,
            "508": 5,
            "e-2008": 5,
        },
        "body_type": {
            "2008": "suv",
            "3008": "suv",
            "306 wagon": "wagon/station",
            "306": "sedan",
            "406": "sedan",
            "5008": "suv",
            "508": "sedan",
            "e-2008": "suv",
        },
        "ground_clearance": {},
    },
    "Porsche": {
        "seating_capacity": {
            "718 cayman style edition": 2,
            "911 carrera 3l sports+": 2,
            "cayenne": 5,
            "panamera": 4,
        },
        "body_type": {
            "718 cayman style edition": "coupe",
            "911 carrera 3l sports+ uk": "coupe",
            "cayenne": "suv",
            "panamera": "sedan",
        },
        "ground_clearance": {},
    },
    "Renault": {
        "seating_capacity": {"kwid": 5},
        "body_type": {"kwid": "hatchback"},
        "ground_clearance": {},
    },
    "SsangYong ": {
        "seating_capacity": {
            "Korando": 5,
            "Kyron": 5,
            "rexton": 7,
            "tivoli": 5,
            "torres ev": 5,
        },
        "body_type": {
            "Korando": "suv",
            "Kyron": "suv",
            "rexton": "suv",
            "tivoli": "suv",
            "torres ev": "suv",
        },
        "ground_clearance": {},
    },
    "Subaru": {
        "seating_capacity": {"crosstrek": 5, "xv": 5},
        "body_type": {"crosstrek": "suv", "xv": "suv"},
        "ground_clearance": {},
    },
    "Suzuki": {
        "seating_capacity": {
            "alto": 4,
            "every": 4,
            "fronx": 5,
            "grand vitara": 5,
            "hustler": 4,
            "ignis": 5,
            "jimny":4,
            "liana":5,
            "s-cross":5,
            "spacia":5,
            "swift":5,
            "vitara":5,
            "wagon r":5,
            "xbee":5
        },
        "body_type": {
            "alto": "hatchback",
            "every": "kei/lightrv/minivan",
            "fronx": "suv",
            "grand vitara": "suv",
            "hustler": "kei/lightrv/hatchback",
            "ignis": "hatchback",
            "jimny":"suv",
            "liana":"sedan",
            "s-cross":"suv",
            "spacia":"kei/microvan",
            "swift":"hatchback",
            "vitara":"suv",
            "wagon r":"hatchback",
            "xbee":"suv"
        },
        "ground_clearance": {},
    },
}
