vehicle_map_2 = {
    "Nissan": {
        "seating_capacity": {
            "almera": 5,
            "ad wagon y11": 5,
            "aura": 5,
            "cefiro": 5,
            "clipper": 5,
            "dayz": 5,
            "dayz highway star": 4,
            "juke": 5,
            "kicks": 5,
            "lafesta": 7,
            "leaf acenta": 5,
            "leaf": 5,
            "magnite": 5,
            "march": 5,
            "navara": 5,
            "note": 5,
            "aura": 5,
            "patrol": 7,
            "primera": 5,
            "qashqai tekna": 5,
            ",roox highway star": 4,
            "sakura": 4,
            "serena e power hs": 7,
            "sunny": 5,
            "sylphy": 5,
            "tiida": 5,
            "x-trail": 5,
            "roox highway star": 4,
        },
        "body_type": {
            "almera": "sedan",
            "ad wagon y11": "station wagon",
            "aura": "hatchback",
            "cefiro": "sedan",
            "clipper": "kei / minivan",
            "dayz": "hatchback",
            "juke": "suv",
            "kicks": "suv",
            "lafesta": "mpv",
            "leaf": "hatchback",
            "magnite": "suv",
            "march": "hatchback",
            "navara": "pickup",
            "note": "hatchback",
            "aura": "hatchback",
            "patrol": "suv",
            "primera": "hatchback / sedan / wagon",
            "qashqai tekna": "suv",
            "roox highway star": "kei / microvan",
            "sakura": "kei / hatchback",
            "serena e power hs": "mpv / minivan",
            "sunny": "sedan",
            "sylphy": "sedan",
            "tiida": "hatchback",
            "tiida latio": "sedan",
            "x-trail": "suv",
            "roox highway star": "kei / microvan",
        },
    },
    "Perodua": {
        "seating_capacity": {"axia": 5, "bezza": 5, "viva elite": 5},
        "body_type": {"axia": "hatchback", "bezza": "sedan", "viva elite": "hatchback"},
    },
    "Peugeot": {
        "seating_capacity": {
            "2008": 5,
            "3008": 5,
            "306 wagon": 5,
            "306": 5,
            "406": 5,
            "5008": 7,
            "508": 5,
            "e-2008": 5,
        },
        "body_type": {
            "2008": "suv",
            "3008": "suv",
            "306 wagon": "wagon / station wagon",
            "306": "sedan",
            "406": "sedan",
            "5008": "suv",
            "508": "sedan",
            "e-2008": "suv",
        },
    },
    "Porsche": {
        "seating_capacity": {
            "718 cayman style edition": 2,
            "911 carrera 3l sports+": 2,
            "cayenne": 5,
            "panamera": 4,
        },
        "body_type": {
            "718 cayman style edition": "coupe",
            "911 carrera 3l sports+": "coupe",
            "cayenne": "suv",
            "panamera": "sedan",
        },
    },
    "Renault": {
        "seating_capacity": {"kwid": 5},
        "body_type": {"kwid": "hatchback"},
    },
    "SsangYong ": {
        "seating_capacity": {
            "Korando": 5,
            "Kyron": 5,
            "rexton": 7,
            "tivoli": 5,
            "torres ev": 5,
        },
        "body_type": {
            "Korando": "suv",
            "Kyron": "suv",
            "rexton": "suv",
            "tivoli": "suv",
            "torres ev": "suv",
        },
    },
    "Subaru": {
        "seating_capacity": {"crosstrek": 5, "xv": 5},
        "body_type": {"crosstrek": "suv", "xv": "suv"},
    },
    "Suzuki": {
        "seating_capacity": {
            "alto": 4,
            "every": 4,
            "fronx": 5,
            "grand vitara": 5,
            "hustler": 4,
            "ignis": 5,
            "jimny": 4,
            "liana": 5,
            "s-cross": 5,
            "spacia": 5,
            "swift": 5,
            "vitara": 5,
            "wagon r": 5,
            "xbee": 5,
        },
        "body_type": {
            "alto": "hatchback",
            "every": "kei / lightrv / minivan",
            "fronx": "suv",
            "grand vitara": "suv",
            "hustler": "kei / lightrv / hatchback",
            "ignis": "hatchback",
            "jimny": "suv",
            "liana": "sedan",
            "s-cross": "suv",
            "spacia": "kei / microvan",
            "swift": "hatchback",
            "vitara": "suv",
            "wagon r": "hatchback",
            "xbee": "suv",
        },
    },
    "Tata": {
        "seating_capacity": {"207d": 2, "nano": 4, "nexon": 5, "tiago": 5, "xenon": 2,"indica":5, "indigo":5},
        "body_type": {
            "207d": "pickup",
            "nano": "hatchback",
            "nexon": "suv",
            "tiago": "hatchback",
            "xenon": "pickup",
            "indica": "hatchback",
            "indigo": "sedan",
        },
        "ground_clearance": {},
    },
    "Tesla": {
        "seating_capacity": {"model 3": 5, "model s": 5, "model x": 7, "model y": 7},
        "body_type": {
            "model 3": "sedan",
            "model s": "sedan",
            "model x": "suv",
            "model y": "suv",
        },
        "ground_clearance": {},
    },
    "Toyota": {
        "seating_capacity": {
            "4runner": 5,
            "allion": 5,
            "alphard": 7,
            "aqua": 5,
            "auris": 5,
            "avanza": 7,
            "axio": 5,
            "belta": 5,
            "camry": 5,
            "c-hr": 5,
            "corolla": 5,
            "crown athlete": 5,
            "crown estate": 5,
            "crown majesta": 5,
            "crown sport": 5,
            "esquire": 7,
            "fielder": 5,
            "fortuner": 7,
            "harrier": 5,
            "hilux": 5,
            "hyryder": 5,
            "ist": 5,
            "land cruiser": 7,
            "land cruiser prado": 7,
            "mark x": 5,
            "passo": 5,
            "pixis l": 5,
            "pixis epoch": 5,
            "pixis": 5,
            "premio": 5,
            "prius": 5,
            "prius zw30": 5,
            "raize": 5,
            "rav4": 5,
            "roomy": 5,
            "vitz": 5,
            "rush": 7,
            "sienta": 7,
            "taisor": 5,
            "tank": 5,
            "urban cruiser taisor": 5,
            "vellfire": 7,
            "veloz": 7,
            "verossa": 5,
            "voxy": 7,
            "yaris": 5,
            "yaris ativ": 5,
            "yaris cross": 5,
            "vanguard": 7,
            "wigo": 5,
        },
        "body_type": {
            "4runner": "suv",
            "allion": "sedan",
            "alphard": "mpv / minivan",
            "aqua": "hatchback",
            "auris": "hatchback",
            "avanza": "mpv / minivan",
            "axio": "sedan",
            "axio fielder g": "station wagon",
            "belta": "sedan",
            "camry": "sedan",
            "c-hr": "suv / crossover",
            "corolla": "sedan",
            "corolla cross": "suv",
            "corolla wxb": "wagon / station wagon",
            "crown athlete": "sedan",
            "crown estate": "wagon / station wagon",
            "crown majesta": "sedan",
            "crown sport": "suv",
            "esquire": "mpv / minivan",
            "fielder": "station wagon",
            "fortuner": "suv",
            "harrier": "suv",
            "hilux": "pickup",
            "hyryder": "suv",
            "ist": "hatchback",
            "land cruiser": "suv",
            "land cruiser prado": "suv",
            "mark x": "sedan",
            "passo": "hatchback",
            "pixis l": "kei / microvan",
            "pixis epoch": "kei / hatchback",
            "pixis": "kei / hatchback",
            "premio": "sedan",
            "prius": "liftback",
            "raize": "suv",
            "rav4": "suv",
            "roomy": "kei / microvan",
            "vitz": "hatchback",
            "rush": "suv",
            "sienta": "mpv / minivan",
            "taisor": "suv",
            "tank": "kei / microvan",
            "urban cruiser taisor": "suv",
            "vellfire": "mpv / minivan",
            "veloz": "mpv / suv",
            "verossa": "sedan",
            "voxy": "mpv / minivan",
            "yaris ativ ": "sedan",
            "yaris ativ g": "sedan",
            "yaris ativ gr sport hev": "sedan",
            "yaris ativ smart": "sedan",
            "yaris ativ sport": "sedan",
            "yaris cross": "suv",
            "yaris cross adventure hev": "suv",
            "yaris cross gr sport hev": "suv",
            "yaris cross hev": "suv",
            "yaris cross modelista hev": "suv",
            "yaris cross smart hev": "suv",
            "yaris cross z hev": "suv",
            "yaris cross z": "suv",
            "yaris cross z adventure hev": "suv",
            "yaris": "hatchback",
            "vanguard": "suv",
            "wigo": "hatchback",

        },
        
    },
    "Volkswagen": {
        "seating_capacity": {"beetle": 4, "golf gt line": 4, "id 4 pro": 5,"id 5 pro":5,"polo":5,"t-cross":5,"tiguan":5,"tiguan allspace":7},
        "body_type": {"beetle": "hatchback", "golf gt line": "convertible", "id 4 pro": "suv","id 5 pro": "suv","polo": "hatchback",
                      "t-cross": "suv","tiguan": "suv"},
    },
    "Zotye": {
        "seating_capacity": {"z100": 5},
        "body_type": {"z100": "hatchback"},
    }
}
